### ISSUE TITLE
java.io.NotSerializableException

### ISSUE THREAD

**Issue by mikhailusachev** [sanity/pairAdjacentViolators#9]
Hello,
i'm using version 1.2.1 and jdk8.

The code in [gist](https://gist.github.com/mikhailusachev/ff9ba2bcd40304317a2a1f6e2b9287dc) throws java.io.NotSerializableException: com.github.sanity.pav.PairAdjacentViolators. 

Is it ok/hard to fix?

**Comment by sanity** [comment]
Should be an easy fix, just make the PairAdjacentViolators implement the Serializable interface, and then write a unit test to verify that it works.  If you can do a pull request I can merge, otherwise I can try to find time to do it.

**Comment by sanity** [comment]
An ugly workaround would be to serialize the isotonicPoints field in the PairAdjacentViolators class, that should be serializable already.  You could then deserialize it later and use those points to initialize a new PairAdjacentViolators class (which would be fast because they're already isotonic).

**Comment by mikhailusachev** [comment]
Hi, made a pull request.

**Comment by sanity** [comment]
It's deployed as version 1.3.0 - thank you!  Out of interest, what are you using the library for?

**Comment by mikhailusachev** [comment]
@sanity Thank you for this lib! I'm using it for image processing.
